project:
  type: website

website:
  title: "Ryan J. Pratt"
  navbar:
    background: dark
    search: true
    right:
      - href: projectslisting.qmd
        text: Projects
      - href: about.qmd
        text: About
  favicon: seedling-solid.svg
  open-graph: true
  twitter-card:
    creator: "@Ryan_J_Pratt"
    card-style: summary
  page-footer: 
    left: "© 2022 Ryan J. Pratt. All rights reserved."
    right: 
      - icon: linkedin
        href: https://linkedin.com/in/ryan-j-pratt/
      - icon: twitter
        href: https://twitter.com/Ryan_J_Pratt/
      - icon: github
        href: https://github.com/ryan-j-pratt/
  cookie-consent:
    type: implied
    style: simple
    palette: dark

format:
  html:
    theme: journal
    css: styles.css
    toc: false

editor: source

