project:
  type: website

website:
  title: "Ryan J. Pratt"
  navbar:
    background: dark
    search: false
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: source

